# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.require_version ">= 1.9.7"

Vagrant.configure("2") do |config|
  $setup_root = <<-SCRIPT
    echo "[DEBUG] ******** setup root BASE VM"
    export DEBIAN_FRONTEND=noninteractive
    echo "Adding repositories and updating list"
    add-apt-repository ppa:longsleep/golang-backports
    apt-get update
    echo "Install packages"
    apt-get install -y --no-remove ntp golang-1.9-go
    echo "remove other users than scion"
    deluser --remove-home ubuntu
    deluser --remove-home vagrant
  SCRIPT
  $cleanup_root = <<-SCRIPT
    echo "[DEBUG] ******** cleanup root BASE VM"
    apt-get autoremove --purge -y
    apt-get clean -y
    apt-get autoclean -y
    
    # Remove bash history
    unset HISTFILE
    rm -f /root/.bash_history
    # Cleanup log files
    find /var/log -type f | while read f; do echo -ne '' > $f; done;
    echo "Zeroing empty space"
    dd if=/dev/zero of=/tmp/EMPTY &>/dev/null || true
    rm -f /tmp/EMPTY
    echo "All clear."
  SCRIPT
  $setup_scion = <<-SCRIPT
    echo "[DEBUG] ******** setup scion BASE VM"
    export DEBIAN_FRONTEND=noninteractive
    su scion -c '/vagrant/scion_install_script.sh -s /vagrant/scion.service -z /vagrant/scion-viz.service -a ~/.bash_aliases -u /vagrant/scionupgrade.sh -t /vagrant/scionupgrade -c'
    echo "Cleaning SCION things"
    $SC/scion.sh stop
    rm $SC/logs/*
    rm -r $SC/gen
    echo "All done."
  SCRIPT
  config.vm.box = "SCIONLabVM-base"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "SCIONLabVM-base"
    vb.customize [ "setextradata", :id, "VBoxInternal/Devices/VMMDev/0/Config/GetHostTimeDisabled", 1 ]
  end
  config.vm.provision "shell", privileged: true, run: "once", inline: $setup_root
  config.vm.provision "shell", privileged: true, run: "once", inline: $setup_scion
  config.vm.provision "shell", privileged: true, run: "once", inline: $cleanup_root
  config.ssh.username = "scion"
  # https://github.com/hashicorp/vagrant/issues/5186
  config.ssh.insert_key = false
end
