FROM ubuntu:16.04
ENV HOME /home/scion
ENV GOPATH $HOME/go
ENV PATH /usr/lib/go-1.9/bin:$GOPATH/bin:$HOME/.local/bin:$PATH

WORKDIR $HOME

# RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y eatmydata sudo && apt-get clean
# # eatmydata to speed up a lot of the building
# RUN ln -s /usr/bin/eatmydata /usr/local/bin/apt-get
# RUN ln -s /usr/bin/eatmydata /usr/local/bin/dpkg
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y software-properties-common
RUN add-apt-repository ppa:gophers/archive
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y golang-1.9-go git sudo
RUN DEBIAN_FRONTEND=noninteractive apt-get upgrade -y



RUN useradd -s /bin/bash scion
RUN echo "scion ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/scion

# # Provide tmpfs at /run/shm while inside non-privileged docker
# RUN ln -s /dev/shm /run/shm

USER scion
RUN sudo chown -R scion: $HOME




ADD ./scion_install_script.sh /tmp/
RUN /tmp/scion_install_script.sh


CMD []
ENTRYPOINT ["/bin/bash", "-l"]
# ENTRYPOINT ["/sbin/init"]
# ENTRYPOINT sudo service zookeeper start ; bash -l
# ENTRYPOINT /sbin/init & bash -l