FROM scionlab-coord-base:0.2
ENV HOME /home/scion
ENV GOPATH $HOME/go
ENV PATH /usr/lib/go-1.9/bin:$GOPATH/bin:$HOME/.local/bin:$PATH

ARG SCIONCOORD=$GOPATH/src/github.com/netsec-ethz/scion-coord
ENV SCIONCOORD $SCIONCOORD

WORKDIR $SCIONCOORD
USER scion

# copy the git files
RUN sudo mkdir -p $SCIONCOORD
RUN sudo chown -R scion:scion $SCIONCOORD
COPY --chown=scion:scion . $SCIONCOORD/

# build and configure
RUN go build
RUN cp $SCIONCOORD/conf/development.conf.default $SCIONCOORD/conf/development.conf
RUN sed -i -- 's/email.pm_server_token = ""/email.pm_server_token = "server_token"/g' "$SCIONCOORD/conf/development.conf"
RUN sed -i -- 's/email.pm_account_token = ""/email.pm_account_token = "account_token"/g' "$SCIONCOORD/conf/development.conf"
RUN sed -i -- 's/^db.host = "127.0.0.1"$/db.host = "mysql"/g'   "$SCIONCOORD/conf/development.conf"


CMD []
ENTRYPOINT ["/bin/bash", "-l"]
