FROM juagargi/scionlab-scion:0.1
ENV HOME /home/scion
ENV GOPATH $HOME/go
ENV PATH /usr/lib/go-1.9/bin:$GOPATH/bin:$HOME/.local/bin:$PATH

WORKDIR $HOME
USER scion

ADD ./scripts/install-scion-coord.sh /tmp/
RUN /tmp/install-scion-coord.sh -d
